import React from "react";
import ResponsiveTable from "./ResponsiveTable";

const TailwindContent = () => {
  const titleStyle = {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#333",
    margin: "20px 0", // Improved spacing
    textAlign: "center", // Center the text
    textTransform: "uppercase", // Uppercase text
    borderBottom: "2px solid #333", // Add an underline
    paddingBottom: "10px", // Space under the underline
  };

  const LayoutData = [
    {
      title: 'Aspect Ratio',
      class: ['aspect-auto', 'aspect-square', 'aspect-video'],
    },
    {
      title: 'responsive and fully fluid viewport',
      class: ['container'],
    },
    {
      title: 'Columns',
      class: [
        'columns-1',
        'columns-2',
        'columns-3',
        'columns-4',
        'columns-5',
        'columns-6',
        'columns-7',
        'columns-8',
        'columns-9',
        'columns-10',
        'columns-11',
        'columns-12',
        'columns-auto',
        'columns-3xs',
        'columns-2xs',
        'columns-xs',
        'columns-sm',
        'columns-md',
        'columns-lg',
        'columns-xl',
        'columns-2xl',
        'columns-3xl',
        'columns-4xl',
        'columns-5xl',
        'columns-6xl',
        'columns-7xl',
      ],
    },
    {
      title: 'Break After',
      class: [
        'break-after-auto',
        'break-after-avoid',
        'break-after-all',
        'break-after-avoid-page',
        'break-after-page',
        'break-after-left',
        'break-after-right',
        'break-after-column',
      ],
    },
    {
      title: 'Break Before',
      class: [
        'break-before-auto',
        'break-before-avoid',
        'break-before-all',
        'break-before-avoid-page',
        'break-before-page',
        'break-before-left',
        'break-before-right',
        'break-before-column',
      ],
    },
    {
      title: 'Break Inside',
      class: [
        'break-inside-auto',
        'break-inside-avoid',
        'break-inside-avoid-page',
        'break-inside-avoid-column',
      ],
    },
    {
      title: 'Box Decoration Break',
      class: ['box-decoration-clone', 'box-decoration-slice'],
    },
    {
      title: 'Box Sizing',
      class: ['box-border', 'box-content'],
    },
    {
      title: 'Display',
      class: [
        'block',
        'inline-block',
        'inline',
        'flex',
        'inline-flex',
        'table',
        'inline-table',
        'table-caption',
        'table-cell',
        'table-column',
        'table-column-group',
        'table-footer-group',
        'table-header-group',
        'table-row-group',
        'table-row',
        'flow-root',
        'grid',
        'inline-grid',
        'contents',
        'list-item',
        'hidden',
      ],
    },
    {
      title: 'Floats',
      class: ['float-right', 'float-left', 'float-none'],
    },
    {
      title: 'Clear',
      class: ['clear-left', 'clear-right', 'clear-both', 'clear-none'],
    },
    {
      title: 'Isolation',
      class: ['isolate', 'isolation-auto'],
    },
    {
      title: 'Object Fit',
      class: [
        'object-contain',
        'object-cover',
        'object-fill',
        'object-none',
        'object-scale-down',
      ],
    },
    {
      title: 'Object Position',
      class: [
        'object-bottom',
        'object-center',
        'object-left',
        'object-left-bottom',
        'object-left-top',
        'object-right',
        'object-right-bottom',
        'object-right-top',
        'object-top',
      ],
    },
    {
      title: 'Overflow',
      class: [
        'overflow-auto',
        'overflow-hidden',
        'overflow-clip',
        'overflow-visible',
        'overflow-scroll',
        'overflow-x-auto',
        'overflow-y-auto',
        'overflow-x-hidden',
        'overflow-y-hidden',
        'overflow-x-clip',
        'overflow-y-clip',
        'overflow-x-visible',
        'overflow-y-visible',
        'overflow-x-scroll',
        'overflow-y-scroll',
      ],
    },
    {
      title: 'Overscroll Behavior',
      class: [
        'overscroll-auto',
        'overscroll-contain',
        'overscroll-none',
        'overscroll-y-auto',
        'overscroll-y-contain',
        'overscroll-y-none',
        'overscroll-x-auto',
        'overscroll-x-contain',
        'overscroll-x-none',
      ],
    },
    {
      title: 'Position',
      class: ['static', 'fixed', 'absolute', 'relative', 'sticky'],
    },
    {
      title: 'Top / Right / Bottom / Left',
      class: ['inset-0', 'inset-x-0', 'inset-y-0', 'start-0', 'end-0', 'top-0', 'right-0'],
    },
    {
      title: 'Visibility',
      class: ['visible', 'invisible', 'collapse'],
    },
    {
      title: 'Z-Index',
      class: ['z-0', 'z-10', 'z-20', 'z-30', 'z-40', 'z-50', 'z-auto'],
    },
    {
      title: '',
      class: ['',],
    },
  ];
  const flexData=[
    {
      title: 'Flex Basis',
      class: [
        'basis-0',
        'basis-1',
        'basis-2',
        'basis-3',
        'basis-4',
        'basis-5',
        'basis-6',
        'basis-7',
        'basis-8',
        'basis-9',
        'basis-10',
        'basis-11',
        'basis-12',
        'basis-14',
        'basis-16',
        'basis-20',
        'basis-24',
        'basis-28',
        'basis-32',
        'basis-36',
        'basis-40',
        'basis-44',
        'basis-48',
        'basis-52',
        'basis-56',
        'basis-60',
        'basis-64',
        'basis-72',
        'basis-80',
        'basis-96',
        'basis-auto',
        'basis-px',
        'basis-0.5',
        'basis-1.5',
        'basis-2.5',
        'basis-3.5',
        'basis-1/2',
        'basis-1/3',
        'basis-2/3',
        'basis-1/4',
        'basis-2/4',
        'basis-3/4',
        'basis-1/5',
        'basis-2/5',
        'basis-3/5',
        'basis-4/5',
        'basis-1/6',
        'basis-2/6',
        'basis-3/6',
        'basis-4/6',
        'basis-5/6',
        'basis-1/12',
        'basis-2/12',
        'basis-3/12',
        'basis-4/12',
        'basis-5/12',
        'basis-6/12',
        'basis-7/12',
        'basis-8/12',
        'basis-9/12',
        'basis-10/12',
        'basis-11/12',
        'basis-full',
      ],
    },
    {
      title: 'Flex Direction',
      class: ['flex-row', 'flex-row-reverse', 'flex-col', 'flex-col-reverse'],
    },
    {
      title: 'Flex Wrap',
      class: ['flex-wrap', 'flex-wrap-reverse', 'flex-nowrap'],
    },
    {
      title: 'Flex',
      class: ['flex-1', 'flex-auto', 'flex-initial', 'flex-none'],
    },
    {
      title: 'Flex Grow',
      class: ['grow', 'grow-0'],
    },
    {
      title: 'Flex Shrink',
      class: ['shrink', 'shrink-0'],
    },
    {
      title: 'Order',
      class: [
        'order-1',
        'order-2',
        'order-3',
        'order-4',
        'order-5',
        'order-6',
        'order-7',
        'order-8',
        'order-9',
        'order-10',
        'order-11',
        'order-12',
        'order-first',
        'order-last',
        'order-none',
      ],
    },
    {
      title: 'Grid Template Columns',
      class: [
        'grid-cols-1',
        'grid-cols-2',
        'grid-cols-3',
        'grid-cols-4',
        'grid-cols-5',
        'grid-cols-6',
        'grid-cols-7',
        'grid-cols-8',
        'grid-cols-9',
        'grid-cols-10',
        'grid-cols-11',
        'grid-cols-12',
        'grid-cols-none',
      ],
    },
    {
      title: 'Grid Column Start / End',
      class: [
        'col-auto',
        'col-span-1',
        'col-span-2',
        'col-span-3',
        'col-span-4',
        'col-span-5',
        'col-span-6',
        'col-span-7',
        'col-span-8',
        'col-span-9',
        'col-span-10',
        'col-span-11',
        'col-span-12',
        'col-span-full',
        'col-start-1',
        'col-start-2',
        'col-start-3',
        'col-start-4',
        'col-start-5',
        'col-start-6',
        'col-start-7',
        'col-start-8',
        'col-start-9',
        'col-start-10',
        'col-start-11',
        'col-start-12',
        'col-start-13',
        'col-start-auto',
        'col-end-1',
        'col-end-2',
        'col-end-3',
        'col-end-4',
        'col-end-5',
        'col-end-6',
        'col-end-7',
        'col-end-8',
        'col-end-9',
        'col-end-10',
        'col-end-11',
        'col-end-12',
        'col-end-13',
        'col-end-auto',
      ],
    },
    {
      title: 'Grid Template Rows',
      class: [
        'grid-rows-1',
        'grid-rows-2',
        'grid-rows-3',
        'grid-rows-4',
        'grid-rows-5',
        'grid-rows-6',
        'grid-rows-none',
      ],
    },
    {
      title: 'Grid Row Start / End',
      class: [
        'row-auto',
        'row-span-1',
        'row-span-2',
        'row-span-3',
        'row-span-4',
        'row-span-5',
        'row-span-6',
        'row-span-full',
        'row-start-1',
        'row-start-2',
        'row-start-3',
        'row-start-4',
        'row-start-5',
        'row-start-6',
        'row-start-7',
        'row-start-auto',
        'row-end-1',
        'row-end-2',
        'row-end-3',
        'row-end-4',
        'row-end-5',
        'row-end-6',
        'row-end-7',
        'row-end-auto',
      ],
    },
    {
      title: 'Grid Auto Flow',
      class: [
        'grid-flow-row',
        'grid-flow-col',
        'grid-flow-dense',
        'grid-flow-row-dense',
        'grid-flow-col-dense',
      ],
    },
    {
      title: 'Grid Auto Columns',
      class: ['auto-cols-auto', 'auto-cols-min', 'auto-cols-max', 'auto-cols-fr'],
    },
    {
      title: 'Grid Auto Rows',
      class: ['auto-rows-auto', 'auto-rows-min', 'auto-rows-max', 'auto-rows-fr'],
    },
    {
      title: 'Gap',
      class: [
        'gap-0',
        'gap-x-0',
        'gap-y-0',
        'gap-px',
        'gap-x-px',
        'gap-y-px',
        'gap-0.5',
        'gap-x-0.5',
        'gap-y-0.5',
        'gap-1',
        'gap-x-1',
        'gap-y-1',
        'gap-1.5',
        'gap-x-1.5',
        'gap-y-1.5',
        'gap-2',
        'gap-x-2',
        'gap-y-2',
        'gap-2.5',
        'gap-x-2.5',
        'gap-y-2.5',
        'gap-3',
        'gap-x-3',
        'gap-y-3',
        'gap-3.5',
        'gap-x-3.5',
        'gap-y-3.5',
        'gap-4',
        'gap-x-4',
        'gap-y-4',
        'gap-5',
        'gap-x-5',
        'gap-y-5',
        'gap-6',
        'gap-x-6',
        'gap-y-6',
        'gap-7',
        'gap-x-7',
        'gap-y-7',
        'gap-8',
        'gap-x-8',
        'gap-y-8',
        'gap-9',
        'gap-x-9',
        'gap-y-9',
        'gap-10',
        'gap-x-10',
        'gap-y-10',
        'gap-11',
        'gap-x-11',
        'gap-y-11',
        'gap-12',
        'gap-x-12',
        'gap-y-12',
        'gap-14',
        'gap-x-14',
        'gap-y-14',
        'gap-16',
        'gap-x-16',
        'gap-y-16',
        'gap-20',
        'gap-x-20',
        'gap-y-20',
        'gap-24',
        'gap-x-24',
        'gap-y-24',
        'gap-28',
        'gap-x-28',
        'gap-y-28',
        'gap-32',
        'gap-x-32',
        'gap-y-32',
        'gap-36',
        'gap-x-36',
        'gap-y-36',
        'gap-40',
        'gap-x-40',
        'gap-y-40',
        'gap-44',
        'gap-x-44',
        'gap-y-44',
        'gap-48',
        'gap-x-48',
        'gap-y-48',
        'gap-52',
        'gap-x-52',
        'gap-y-52',
        'gap-56',
        'gap-x-56',
        'gap-y-56',
        'gap-60',
        'gap-x-60',
        'gap-y-60',
        'gap-64',
        'gap-x-64',
        'gap-y-64',
        'gap-72',
        'gap-x-72',
        'gap-y-72',
        'gap-80',
        'gap-x-80',
        'gap-y-80',
        'gap-96',
        'gap-x-96',
        'gap-y-96',
      ],
    },
    {
      title: 'Justify Content',
      class: [
        'justify-normal',
        'justify-start',
        'justify-end',
        'justify-center',
        'justify-between',
        'justify-around',
        'justify-evenly',
        'justify-stretch',
      ],
    },
    {
      title: 'Justify Items',
      class: [
        'justify-items-start',
        'justify-items-end',
        'justify-items-center',
        'justify-items-stretch',
      ],
    },
    {
      title: 'Justify Self',
      class: [
        'justify-self-auto',
        'justify-self-start',
        'justify-self-end',
        'justify-self-center',
        'justify-self-stretch',
      ],
    },
    {
      title: 'Align Content',
      class: [
        'content-normal',
        'content-center',
        'content-start',
        'content-end',
        'content-between',
        'content-around',
        'content-evenly',
        'content-baseline',
        'content-stretch',
      ],
    },
    {
      title: 'Align Items',
      class: [
        'items-start',
        'items-end',
        'items-center',
        'items-baseline',
        'items-stretch',
      ],
    },
    {
      title: 'Align Self',
      class: [
        'self-auto',
        'self-start',
        'self-end',
        'self-center',
        'self-stretch',
        'self-baseline',
      ],
    },
    {
      title: 'Place Content',
      class: [
        'place-content-center',
        'place-content-start',
        'place-content-end',
        'place-content-between',
        'place-content-around',
        'place-content-evenly',
        'place-content-baseline',
        'place-content-stretch',
      ],
    },
    {
      title: 'Place Items',
      class: [
        'place-items-start',
        'place-items-end',
        'place-items-center',
        'place-items-baseline',
        'place-items-stretch',
      ],
    },
    {
      title: 'Place Self',
      class: [
        'place-self-auto',
        'place-self-start',
        'place-self-end',
        'place-self-center',
        'place-self-stretch',
      ],
    },

  ]
  const spacingData=[
    {
      title: 'Padding',
      class: [
        'p-0',
        'px-0',
        'py-0',
        'ps-0',
        'pe-0',
        'pt-0',
        'pr-0',
        'pb-0',
        'pl-0',
        'p-px',
        'px-px',
        'py-px',
        'ps-px',
        'pe-px',
        'pt-px',
        'pr-px',
        'pb-px',
        'pl-px',
        'p-0.5',
        'px-0.5',
        'py-0.5',
        'ps-0.5',
        'pe-0.5',
        'pt-0.5',
        'pr-0.5',
        'pb-0.5',
        'pl-0.5',
        'p-1',
        'px-1',
        'py-1',
        'ps-1',
        'pe-1',
        'pt-1',
        'pr-1',
        'pb-1',
        'pl-1',
        'p-1.5',
        'px-1.5',
        'py-1.5',
        'ps-1.5',
        'pe-1.5',
        'pt-1.5',
        'pr-1.5',
        'pb-1.5',
        'pl-1.5',
        'p-2',
        'px-2',
        'py-2',
        'ps-2',
        'pe-2',
        'pt-2',
        'pr-2',
        'pb-2',
        'pl-2',
        'p-2.5',
        'px-2.5',
        'py-2.5',
        'ps-2.5',
        'pe-2.5',
        'pt-2.5',
        'pr-2.5',
        'pb-2.5',
        'pl-2.5',
        'p-3',
        'px-3',
        'py-3',
        'ps-3',
        'pe-3',
        'pt-3',
        'pr-3',
        'pb-3',
        'pl-3',
        'p-3.5',
        'px-3.5',
        'py-3.5',
        'ps-3.5',
        'pe-3.5',
        'pt-3.5',
        'pr-3.5',
        'pb-3.5',
        'pl-3.5',
        'p-4',
        'px-4',
        'py-4',
        'ps-4',
        'pe-4',
        'pt-4',
        'pr-4',
        'pb-4',
        'pl-4',
        'p-5',
        'px-5',
        'py-5',
        'ps-5',
        'pe-5',
        'pt-5',
        'pr-5',
        'pb-5',
        'pl-5',
        'p-6',
        'px-6',
        'py-6',
        'ps-6',
        'pe-6',
        'pt-6',
        'pr-6',
        'pb-6',
        'pl-6',
        'p-7',
        'px-7',
        'py-7',
        'ps-7',
        'pe-7',
        'pt-7',
        'pr-7',
        'pb-7',
        'pl-7',
        'p-8',
        'px-8',
        'py-8',
        'ps-8',
        'pe-8',
        'pt-8',
        'pr-8',
        'pb-8',
        'pl-8',
        'p-9',
        'px-9',
        'py-9',
        'ps-9',
        'pe-9',
        'pt-9',
        'pr-9',
        'pb-9',
        'pl-9',
        'p-10',
        'px-10',
        'py-10',
        'ps-10',
        'pe-10',
        'pt-10',
        'pr-10',
        'pb-10',
        'pl-10',
        'p-11',
        'px-11',
        'py-11',
        'ps-11',
        'pe-11',
        'pt-11',
        'pr-11',
        'pb-11',
        'pl-11',
        'p-12',
        'px-12',
        'py-12',
        'ps-12',
        'pe-12',
        'pt-12',
        'pr-12',
        'pb-12',
        'pl-12',
        'p-14',
        'px-14',
        'py-14',
        'ps-14',
        'pe-14',
        'pt-14',
        'pr-14',
        'pb-14',
        'pl-14',
        'p-16',
        'px-16',
        'py-16',
        'ps-16',
        'pe-16',
        'pt-16',
        'pr-16',
        'pb-16',
        'pl-16',
        'p-20',
        'px-20',
        'py-20',
        'ps-20',
        'pe-20',
        'pt-20',
        'pr-20',
        'pb-20',
        'pl-20',
        'p-24',
        'px-24',
        'py-24',
        'ps-24',
        'pe-24',
        'pt-24',
        'pr-24',
        'pb-24',
        'pl-24',
        'p-28',
        'px-28',
        'py-28',
        'ps-28',
        'pe-28',
        'pt-28',
        'pr-28',
        'pb-28',
        'pl-28',
        'p-32',
        'px-32',
        'py-32',
        'ps-32',
        'pe-32',
        'pt-32',
        'pr-32',
        'pb-32',
        'pl-32',
        'p-36',
        'px-36',
        'py-36',
        'ps-36',
        'pe-36',
        'pt-36',
        'pr-36',
        'pb-36',
        'pl-36',
        'p-40',
        'px-40',
        'py-40',
        'ps-40',
        'pe-40',
        'pt-40',
        'pr-40',
        'pb-40',
        'pl-40',
        'p-44',
        'px-44',
        'py-44',
        'ps-44',
        'pe-44',
        'pt-44',
        'pr-44',
        'pb-44',
        'pl-44',
        'p-48',
        'px-48',
        'py-48',
        'ps-48',
        'pe-48',
        'pt-48',
        'pr-48',
        'pb-48',
        'pl-48',
        'p-52',
        'px-52',
        'py-52',
        'ps-52',
        'pe-52',
        'pt-52',
        'pr-52',
        'pb-52',
        'pl-52',
        'p-56',
        'px-56',
        'py-56',
        'ps-56',
        'pe-56',
        'pt-56',
        'pr-56',
        'pb-56',
        'pl-56',
        'p-60',
        'px-60',
        'py-60',
        'ps-60',
        'pe-60',
        'pt-60',
        'pr-60',
        'pb-60',
        'pl-60',
        'p-64',
        'px-64',
        'py-64',
        'ps-64',
        'pe-64',
        'pt-64',
        'pr-64',
        'pb-64',
        'pl-64',
        'p-72',
        'px-72',
        'py-72',
        'ps-72',
        'pe-72',
        'pt-72',
        'pr-72',
        'pb-72',
        'pl-72',
        'p-80',
        'px-80',
        'py-80',
        'ps-80',
        'pe-80',
        'pt-80',
        'pr-80',
        'pb-80',
        'pl-80',
        'p-96',
        'px-96',
        'py-96',
        'ps-96',
        'pe-96',
        'pt-96',
        'pr-96',
        'pb-96',
        'pl-96',
      ],
    },
    {
      title: 'Margin',
      class: [
        'm-0',
        'mx-0',
        'margin-right-0',
        'my-0',
        'margin-bottom-0',
        'margin-inline-start-0',
        'margin-inline-end-0',
        'mt-0',
        'mr-0',
        'mb-0',
        'ml-0',
        'm-px',
        'mx-px',
        'margin-right-px',
        'my-px',
        'margin-bottom-px',
        'margin-inline-start-px',
        'margin-inline-end-px',
        'mt-px',
        'mr-px',
        'mb-px',
        'ml-px',
        'm-0.5',
        'mx-0.5',
        'margin-right-0.5',
        'my-0.5',
        'margin-bottom-0.5',
        'margin-inline-start-0.5',
        'margin-inline-end-0.5',
        'mt-0.5',
        'mr-0.5',
        'mb-0.5',
        'ml-0.5',
        'm-1',
        'mx-1',
        'margin-right-1',
        'my-1',
        'margin-bottom-1',
        'margin-inline-start-1',
        'margin-inline-end-1',
        'mt-1',
        'mr-1',
        'mb-1',
        'ml-1',
        'm-1.5',
        'mx-1.5',
        'margin-right-1.5',
        'my-1.5',
        'margin-bottom-1.5',
        'margin-inline-start-1.5',
        'margin-inline-end-1.5',
        'mt-1.5',
        'mr-1.5',
        'mb-1.5',
        'ml-1.5',
        'm-2',
        'mx-2',
        'margin-right-2',
        'my-2',
        'margin-bottom-2',
        'margin-inline-start-2',
        'margin-inline-end-2',
        'mt-2',
        'mr-2',
        'mb-2',
        'ml-2',
        'm-2.5',
        'mx-2.5',
        'margin-right-2.5',
        'my-2.5',
        'margin-bottom-2.5',
        'margin-inline-start-2.5',
        'margin-inline-end-2.5',
        'mt-2.5',
        'mr-2.5',
        'mb-2.5',
        'ml-2.5',
        'm-3',
        'mx-3',
        'margin-right-3',
        'my-3',
        'margin-bottom-3',
        'margin-inline-start-3',
        'margin-inline-end-3',
        'mt-3',
        'mr-3',
        'mb-3',
        'ml-3',
        'm-3.5',
        'mx-3.5',
        'margin-right-3.5',
        'my-3.5',
        'margin-bottom-3.5',
        'margin-inline-start-3.5',
        'margin-inline-end-3.5',
        'mt-3.5',
        'mr-3.5',
        'mb-3.5',
        'ml-3.5',
        'm-4',
        'mx-4',
        'margin-right-4',
        'my-4',
        'margin-bottom-4',
        'margin-inline-start-4',
        'margin-inline-end-4',
        'mt-4',
        'mr-4',
        'mb-4',
        'ml-4',
        'm-5',
        'mx-5',
        'margin-right-5',
        'my-5',
        'margin-bottom-5',
        'margin-inline-start-5',
        'margin-inline-end-5',
        'mt-5',
        'mr-5',
        'mb-5',
        'ml-5',
        'm-6',
        'mx-6',
        'margin-right-6',
        'my-6',
        'margin-bottom-6',
        'margin-inline-start-6',
        'margin-inline-end-6',
        'mt-6',
        'mr-6',
        'mb-6',
        'ml-6',
        'm-7',
        'mx-7',
        'margin-right-7',
        'my-7',
        'margin-bottom-7',
        'margin-inline-start-7',
        'margin-inline-end-7',
        'mt-7',
        'mr-7',
        'mb-7',
        'ml-7',
        'm-8',
        'mx-8',
        'margin-right-8',
        'my-8',
        'margin-bottom-8',
        'margin-inline-start-8',
        'margin-inline-end-8',
        'mt-8',
        'mr-8',
        'mb-8',
        'ml-8',
        'm-9',
        'mx-9',
        'margin-right-9',
        'my-9',
        'margin-bottom-9',
        'margin-inline-start-9',
        'margin-inline-end-9',
        'mt-9',
        'mr-9',
        'mb-9',
        'ml-9',
        'm-10',
        'mx-10',
        'margin-right-10',
        'my-10',
        'margin-bottom-10',
        'margin-inline-start-10',
        'margin-inline-end-10',
        'mt-10',
        'mr-10',
        'mb-10',
        'ml-10',
        'm-11',
        'mx-11',
        'margin-right-11',
        'my-11',
        'margin-bottom-11',
        'margin-inline-start-11',
        'margin-inline-end-11',
        'mt-11',
        'mr-11',
        'mb-11',
        'ml-11',
        'm-12',
        'mx-12',
        'margin-right-12',
        'my-12',
        'margin-bottom-12',
        'margin-inline-start-12',
        'margin-inline-end-12',
        'mt-12',
        'mr-12',
        'mb-12',
        'ml-12',
      ],
    },
    {
      title: 'Space Between',
      class: [
        'space-x-0',
        'space-y-0',
        'space-x-0.5',
        'space-y-0.5',
        'space-x-1',
        'space-y-1',
        'space-x-1.5',
        'space-y-1.5',
        'space-x-2',
        'space-y-2',
        'space-x-2.5',
        'space-y-2.5',
        'space-x-3',
        'space-y-3',
        'space-x-3.5',
        'space-y-3.5',
        'space-x-4',
        'space-y-4',
        'space-x-5',
        'space-y-5',
        'space-x-6',
        'space-y-6',
        'space-x-7',
        'space-y-7',
        'space-x-8',
        'space-y-8',
        'space-x-9',
        'space-y-9',
        'space-x-10',
        'space-y-10',
        'space-x-11',
        'space-y-11',
        'space-x-12',
        'space-y-12',
        'space-x-14',
        'space-y-14',
        'space-x-16',
        'space-y-16',
        'space-x-20',
        'space-y-20',
        'space-x-24',
        'space-y-24',
        'space-x-28',
        'space-y-28',
        'space-x-32',
        'space-y-32',
        'space-x-36',
        'space-y-36',
        'space-x-40',
        'space-y-40',
        'space-x-44',
        'space-y-44',
        'space-x-48',
        'space-y-48',
        'space-x-52',
        'space-y-52',
        'space-x-56',
        'space-y-56',
        'space-x-60',
        'space-y-60',
        'space-x-64',
        'space-y-64',
        'space-x-72',
        'space-y-72',
        'space-x-80',
        'space-y-80',
        'space-x-96',
        'space-y-96',
        'space-x-px',
        'space-y-px',
        'space-y-reverse',
        'space-x-reverse',
      ],
    },
  ]
  const sizingData=[
    {
      title: 'Width',
      class: [
        'w-0',
        'w-px',
        'w-0.5',
        'w-1',
        'w-1.5',
        'w-2',
        'w-2.5',
        'w-3',
        'w-3.5',
        'w-4',
        'w-5',
        'w-6',
        'w-7',
        'w-8',
        'w-9',
        'w-10',
        'w-11',
        'w-12',
        'w-14',
        'w-16',
        'w-20',
        'w-24',
        'w-28',
        'w-32',
        'w-36',
        'w-40',
        'w-44',
        'w-48',
        'w-52',
        'w-56',
        'w-60',
        'w-64',
        'w-72',
        'w-80',
        'w-96',
        'w-auto',
        'w-1/2',
        'w-1/3',
        'w-2/3',
        'w-1/4',
        'w-2/4',
        'w-3/4',
        'w-1/5',
        'w-2/5',
        'w-3/5',
        'w-4/5',
        'w-1/6',
        'w-2/6',
        'w-3/6',
        'w-4/6',
        'w-5/6',
        'w-1/12',
        'w-2/12',
        'w-3/12',
        'w-4/12',
        'w-5/12',
        'w-6/12',
        'w-7/12',
        'w-8/12',
        'w-9/12',
        'w-10/12',
        'w-11/12',
        'w-full',
        'w-screen',
        'w-min',
        'w-max',
        'w-fit',
      ],
    },
    {
      title: 'Min-Width',
      class: [
        'min-w-0',
        'min-w-full',
        'min-w-min',
        'min-w-max',
        'min-w-fit',
      ],
    },
    {
      title: 'Max-Width',
      class: [
        'max-w-0',
        'max-w-none',
        'max-w-xs',
        'max-w-sm',
        'max-w-md',
        'max-w-lg',
        'max-w-xl',
        'max-w-2xl',
        'max-w-3xl',
        'max-w-4xl',
        'max-w-5xl',
        'max-w-6xl',
        'max-w-7xl',
        'max-w-full',
        'max-w-min',
        'max-w-max',
        'max-w-fit',
        'max-w-prose',
        'max-w-screen-sm',
        'max-w-screen-md',
        'max-w-screen-lg',
        'max-w-screen-xl',
        'max-w-screen-2xl',
      ],
    },
    {
      title: 'Height',
      class: [
        'h-0', 'h-px', 'h-0.5', 'h-1', 'h-1.5', 'h-2', 'h-2.5', 'h-3', 'h-3.5',
        'h-4', 'h-5', 'h-6', 'h-7', 'h-8', 'h-9', 'h-10', 'h-11', 'h-12', 'h-14',
        'h-16', 'h-20', 'h-24', 'h-28', 'h-32', 'h-36', 'h-40', 'h-44', 'h-48',
        'h-52', 'h-56', 'h-60', 'h-64', 'h-72', 'h-80', 'h-96', 'h-auto', 'h-1/2',
        'h-1/3', 'h-2/3', 'h-1/4', 'h-2/4', 'h-3/4', 'h-1/5', 'h-2/5', 'h-3/5',
        'h-4/5', 'h-1/6', 'h-2/6', 'h-3/6', 'h-4/6', 'h-5/6', 'h-full', 'h-screen',
        'h-min', 'h-max', 'h-fit',
      ],
    },
    {
      title: 'Min-Height',
      class: [
        'min-h-0',
        'min-h-full',
        'min-h-screen',
        'min-h-min',
        'min-h-max',
        'min-h-fit',
      ],
    },
    {
      title: 'Max-Height',
      class: [
        'max-h-0',
        'max-h-px',
        'max-h-0.5',
        'max-h-1',
        'max-h-1.5',
        'max-h-2',
        'max-h-2.5',
        'max-h-3',
        'max-h-3.5',
        'max-h-4',
        'max-h-5',
        'max-h-6',
        'max-h-7',
        'max-h-8',
        'max-h-9',
        'max-h-10',
        'max-h-11',
        'max-h-12',
        'max-h-14',
        'max-h-16',
        'max-h-20',
        'max-h-24',
        'max-h-28',
        'max-h-32',
        'max-h-36',
        'max-h-40',
        'max-h-44',
        'max-h-48',
        'max-h-52',
        'max-h-56',
        'max-h-60',
        'max-h-64',
        'max-h-72',
        'max-h-80',
        'max-h-96',
        'max-h-none',
        'max-h-full',
        'max-h-screen',
        'max-h-min',
        'max-h-max',
        'max-h-fit',
      ],
    },
  ]
  const typographyData=[
    {
      title: 'Font Family',
      class: [
        'font-sans',
        'font-serif',
        'font-mono',
      ],
    },
    {
      title: 'Font Size',
      class: [
        'text-xs',
        'text-sm',
        'text-base',
        'text-lg',
        'text-xl',
        'text-2xl',
        'text-3xl',
        'text-4xl',
        'text-5xl',
        'text-6xl',
        'text-7xl',
        'text-8xl',
        'text-9xl',
      ],
    },
    {
      title: 'Font Smoothing',
      class: ['antialiased', 'subpixel-antialiased'],
    },
    {
      title: 'Font Style',
      class: ['italic', 'not-italic'],
    },
    {
      title: 'Font Weight',
      class: [
        'font-thin',
        'font-extralight',
        'font-light',
        'font-normal',
        'font-medium',
        'font-semibold',
        'font-bold',
        'font-extrabold',
        'font-black',
      ],
    },
    {
      title: 'Font Variant Numeric',
      class: [
        'normal-nums',
        'ordinal',
        'slashed-zero',
        'lining-nums',
        'oldstyle-nums',
        'proportional-nums',
        'tabular-nums',
        'diagonal-fractions',
        'stacked-fractions',
      ],
    },
    {
      title: 'Letter Spacing',
      class: [
        'tracking-tighter',
        'tracking-tight',
        'tracking-normal',
        'tracking-wide',
        'tracking-wider',
        'tracking-widest',
      ],
    },
    {
      title: 'Line Clamp',
      class: [
        'line-clamp-1',
        'line-clamp-2',
        'line-clamp-3',
        'line-clamp-4',
        'line-clamp-5',
        'line-clamp-6',
        'line-clamp-none',
      ],
    },
    {
      title: 'Line Height',
      class: [
        'leading-3',      /* line-height: .75rem; 12px */
        'leading-4',      /* line-height: 1rem; 16px */
        'leading-5',      /* line-height: 1.25rem; 20px */
        'leading-6',      /* line-height: 1.5rem; 24px */
        'leading-7',      /* line-height: 1.75rem; 28px */
        'leading-8',      /* line-height: 2rem; 32px */
        'leading-9',      /* line-height: 2.25rem; 36px */
        'leading-10',     /* line-height: 2.5rem; 40px */
        'leading-none',   /* line-height: 1; */
        'leading-tight',  /* line-height: 1.25; */
        'leading-snug',   /* line-height: 1.375; */
        'leading-normal', /* line-height: 1.5; */
        'leading-relaxed',/* line-height: 1.625; */
        'leading-loose',  /* line-height: 2; */
      ],
    },
    {
      title: 'List Style Image',
      class: ['list-image-none'], /* list-style-image: none; */
    },
    {
      title: 'List Style Position',
      class: [
        'list-inside',  /* list-style-position: inside; */
        'list-outside', /* list-style-position: outside; */
      ],
    },
    {
      title: 'List Style Type',
      class: ['list-none', 'list-disc', 'list-decimal'],
    },
    {
      title: 'Text Align',
      class: ['text-left', 'text-center', 'text-right', 'text-justify', 'text-start', 'text-end'],
    },
    {
      title: 'Text Color',
      class: [
        'text-inherit',
        'text-current',
        'text-transparent',
        'text-black',
        'text-white',
        'text-slate-50',
        'text-slate-100',
        'text-slate-200',
        'text-slate-300',
        'text-slate-400',
        'text-slate-500',
        'text-slate-600',
        'text-slate-700',
        'text-slate-800',
        'text-slate-900',
        'text-slate-950',
        'text-gray-50',
        // Add more classes as needed
      ],
    },
    {
      title: 'Text Decoration',
      class: ['underline', 'overline', 'line-through', 'no-underline'],
    },
    {
      title: 'Text Decoration Color',
      class: [
        'decoration-inherit',
        'decoration-current',
        'decoration-transparent',
        'decoration-black',
        'decoration-white',
        'decoration-slate-50',
        'decoration-slate-100',
        'decoration-slate-200',
        'decoration-slate-300',
        'decoration-slate-400',
        'decoration-slate-500',
        'decoration-slate-600',
        'decoration-slate-700',
        'decoration-slate-800',
        'decoration-slate-900',
        'decoration-slate-950',
        'decoration-gray-50',
      ],
    },
    {
      title: 'Text Decoration Style',
      class: ['decoration-solid', 'decoration-double', 'decoration-dotted', 'decoration-dashed', 'decoration-wavy'],
    },
    {
      title: 'Text Decoration Thickness',
      class: ['decoration-auto', 'decoration-from-font', 'decoration-0', 'decoration-1', 'decoration-2', 'decoration-4', 'decoration-8'],
    },
    {
      title: 'Text Underline Offset',
      class: [
        'underline-offset-auto',
        'underline-offset-0',
        'underline-offset-1',
        'underline-offset-2',
        'underline-offset-4',
        'underline-offset-8',
      ],
    },
    {
      title: 'Text Transform',
      class: ['uppercase', 'lowercase', 'capitalize', 'normal-case'],
    },
    {
      title: 'Text Overflow',
      class: ['truncate', 'text-ellipsis', 'text-clip'],
    },
    {
      title: 'Text Indent',
      class: [
        'indent-0',
        'indent-px',
        'indent-0.5',
        'indent-1',
        'indent-1.5',
        'indent-2',
        'indent-2.5',
        'indent-3',
        'indent-3.5',
        'indent-4',
        'indent-5',
        'indent-6',
        'indent-7',
        'indent-8',
        'indent-9',
        'indent-10',
        'indent-11',
        'indent-12',
        'indent-14',
        'indent-16',
        'indent-20',
        'indent-24',
        'indent-28',
        'indent-32',
        'indent-36',
        'indent-40',
        'indent-44',
        'indent-48',
        'indent-52',
        'indent-56',
        'indent-60',
        'indent-64',
        'indent-72',
        'indent-80',
        'indent-96',
      ],
    },
    {
      title: 'Vertical Align',
      class: [
        'align-baseline',
        'align-top',
        'align-middle',
        'align-bottom',
        'align-text-top',
        'align-text-bottom',
        'align-sub',
        'align-super',
      ],
    },
    {
      title: 'Whitespace',
      class: [
        'whitespace-normal',
        'whitespace-nowrap',
        'whitespace-pre',
        'whitespace-pre-line',
        'whitespace-pre-wrap',
        'whitespace-break-spaces',
      ],
    },
    {
      title: 'Word Break',
      class: ['break-normal', 'break-words', 'break-all', 'break-keep'],
    },
    {
      title: 'Hyphens',
      class: ['hyphens-none', 'hyphens-manual', 'hyphens-auto'],
    },
    {
      title: 'Content',
      class: ['content-none'],
    },
  ]
  const backgroundsData=[
    {
      title: 'Background Attachment',
      class: ['bg-fixed', 'bg-local', 'bg-scroll'],
    },
    {
      title: 'Background Clip',
      class: ['bg-clip-border', 'bg-clip-padding', 'bg-clip-content', 'bg-clip-text'],
    },
    {
      title: 'Background Color',
      class: [
        'bg-inherit',
        'bg-current',
        'bg-transparent',
        'bg-black',
        'bg-white',
        'bg-slate-50',
        'bg-slate-100',
        'bg-slate-200',
        'bg-slate-300',
        'bg-slate-400',
        'bg-slate-500',
      ],
    },
    {
      title: 'Background Origin',
      class: ['bg-origin-border', 'bg-origin-padding', 'bg-origin-content'],
    },
    {
      title: 'Background Position',
      class: [
        'bg-bottom',
        'bg-center',
        'bg-left',
        'bg-left-bottom',
        'bg-left-top',
        'bg-right',
        'bg-right-bottom',
        'bg-right-top',
        'bg-top',
      ],
    },
    {
      title: 'Background Repeat',
      class: [
        'bg-repeat',
        'bg-no-repeat',
        'bg-repeat-x',
        'bg-repeat-y',
        'bg-repeat-round',
        'bg-repeat-space',
      ],
    },
    {
      title: 'Background Size',
      class: ['bg-auto', 'bg-cover', 'bg-contain'],
    },
    {
      title: 'Background Image',
      class: ['bg-none', 'bg-gradient-to-t', 'bg-gradient-to-tr', 'bg-gradient-to-r', 'bg-gradient-to-br', 'bg-gradient-to-b', 'bg-gradient-to-bl', 'bg-gradient-to-l', 'bg-gradient-to-tl'],
    },
    {
      title: 'Gradient Color Stops',
      class: [
        'from-inherit',
        'from-current',
        'from-transparent',
        'from-black',
      ],
    },
  ]
  const bordersData=[
    {
      title: 'Border Radius',
      class: [
        'rounded-none',
        'rounded-sm',
        'rounded',
        'rounded-md',
        'rounded-lg',
        'rounded-xl',
        'rounded-2xl',
        'rounded-3xl',
        'rounded-full',
        'rounded-s-none',
        'rounded-s-sm',
        'rounded-s',
        'rounded-s-md',
        'rounded-s-lg',
        'rounded-s-xl',
        'rounded-s-2xl',
        'rounded-s-3xl',
        'rounded-s-full',
        'rounded-e-none',
        'rounded-e-sm',
        'rounded-e',
        'rounded-e-md',
        'rounded-e-lg',
        'rounded-e-xl',
        'rounded-e-2xl',
        'rounded-e-3xl',
        'rounded-e-full',
        'rounded-t-none',
        'rounded-t-sm',
        'rounded-t',
        'rounded-t-md',
        'rounded-t-lg',
        'rounded-t-xl',
        'rounded-t-2xl',
        'rounded-t-3xl',
        'rounded-t-full',
        'rounded-r-none',
        'rounded-r-sm',
        'rounded-r',
        'rounded-r-md',
        'rounded-r-lg',
        'rounded-r-xl',
        'rounded-r-2xl',
        'rounded-r-3xl',
        'rounded-r-full',
        'rounded-b-none',
        'rounded-b-sm',
        'rounded-b',
        'rounded-b-md',
        'rounded-b-lg',
        'rounded-b-xl',
        'rounded-b-2xl',
        'rounded-b-3xl',
        'rounded-b-full',
        'rounded-l-none',
        'rounded-l-sm',
        'rounded-l',
        'rounded-l-md',
        'rounded-l-lg',
        'rounded-l-xl',
        'rounded-l-2xl',
        'rounded-l-3xl',
        'rounded-l-full',
        'rounded-ss-none',
        'rounded-ss-sm',
        'rounded-ss',
        'rounded-ss-md',
        'rounded-ss-lg',
        'rounded-ss-xl',
        'rounded-ss-2xl',
        'rounded-ss-3xl',
        'rounded-ss-full',
        'rounded-se-none',
        'rounded-se-sm',
        'rounded-se',
        'rounded-se-md',
        'rounded-se-lg',
        'rounded-se-xl',
        'rounded-se-2xl',
        'rounded-se-3xl',
        'rounded-se-full',
        'rounded-ee-none',
        'rounded-ee-sm',
        'rounded-ee',
        'rounded-ee-md',
        'rounded-ee-lg',
        'rounded-ee-xl',
        'rounded-ee-2xl',
        'rounded-ee-3xl',
        'rounded-ee-full',
        'rounded-es-none',
        'rounded-es-sm',
        'rounded-es',
        'rounded-es-md',
        'rounded-es-lg',
        'rounded-es-xl',
        'rounded-es-2xl',
        'rounded-es-3xl',
        'rounded-es-full',
        'rounded-tl-none',
        'rounded-tl-sm',
        'rounded-tl',
        'rounded-tl-md',
        'rounded-tl-lg',
        'rounded-tl-xl',
        'rounded-tl-2xl',
        'rounded-tl-3xl',
        'rounded-tl-full',
        'rounded-tr-none',
        'rounded-tr-sm',
        'rounded-tr',
        'rounded-tr-md',
        'rounded-tr-lg',
        'rounded-tr-xl',
        'rounded-tr-2xl',
        'rounded-tr-3xl',
        'rounded-tr-full',
        'rounded-br-none',
        'rounded-br-sm',
        'rounded-br',
        'rounded-br-md',
        'rounded-br-lg',
        'rounded-br-xl',
        'rounded-br-2xl',
        'rounded-br-3xl',
        'rounded-br-full',
        'rounded-bl-none',
        'rounded-bl-sm',
        'rounded-bl',
        'rounded-bl-md',
        'rounded-bl-lg',
        'rounded-bl-xl',
        'rounded-bl-2xl',
        'rounded-bl-3xl',
        'rounded-bl-full',
      ],
    },
    {
      title: 'Border Width',
      class: [
        'border-0',
        'border-2',
        'border-4',
        'border-8',
        'border',
        'border-x-0',
        'border-x-2',
        'border-x-4',
        'border-x-8',
        'border-x',
        'border-y-0',
        'border-y-2',
        'border-y-4',
        'border-y-8',
        'border-y',
        'border-s-0',
        'border-s-2',
        'border-s-4',
        'border-s-8',
        'border-s',
        'border-e-0',
        'border-e-2',
        'border-e-4',
        'border-e-8',
        'border-e',
        'border-t-0',
        'border-t-2',
        'border-t-4',
        'border-t-8',
        'border-t',
        'border-r-0',
        'border-r-2',
        'border-r-4',
        'border-r-8',
        'border-r',
        'border-b-0',
        'border-b-2',
        'border-b-4',
        'border-b-8',
        'border-b',
        'border-l-0',
        'border-l-2',
        'border-l-4',
        'border-l-8',
        'border-l',
      ],
    },
    {
      title: 'Border Color',
      class: [
        'border-inherit',
        'border-current',
        'border-transparent',
        'border-black',
        'border-white',
        'border-slate-50',
        'border-slate-100',
        'border-slate-200',
        'border-slate-300',
      ],
    },
    {
      title: 'Border Style',
      class: ['border-solid', 'border-dashed', 'border-dotted', 'border-double', 'border-hidden', 'border-none'],
    },
    {
      title: 'Divide Width',
      class: [
        'divide-x-0',
        'divide-x-2',
        'divide-x-4',
        'divide-x-8',
        'divide-x',
        'divide-y-0',
        'divide-y-2',
        'divide-y-4',
        'divide-y-8',
        'divide-y',
        'divide-y-reverse',
        'divide-x-reverse',
      ],
    },

    {
      title: 'Divide Color',
      class: [
        'divide-inherit',
        'divide-current',
        'divide-transparent',
        'divide-black',
        'divide-white',
        'divide-slate-50',
        'divide-slate-100',
        'divide-slate-200',
        'divide-slate-300',
      ],
    },
    {
      title: 'Divide Style',
      class: [
        'divide-solid',
        'divide-dashed',
        'divide-dotted',
        'divide-double',
        'divide-none',
      ],
    },
    {
      title: 'Outline Width',
      class: ['outline-0', 'outline-1', 'outline-2', 'outline-4', 'outline-8'],
    },
    {
      title: 'Outline Color',
      class: [
        'outline-inherit',
        'outline-current',
        'outline-transparent',
        'outline-black',
        'outline-white',
        'outline-slate-50',
        'outline-slate-100',
        'outline-slate-200',
        'outline-slate-300',
      ],
    },
    {
      title: 'Outline Style',
      class: ['outline-none', 'outline-offset-0', 'outline-offset-1', 'outline-offset-2', 'outline-offset-4', 'outline-offset-8', 'outline-dashed', 'outline-dotted', 'outline-double'],
    },
    {
      title: 'Outline Offset',
      class: ['outline-offset-0', 'outline-offset-1', 'outline-offset-2', 'outline-offset-4', 'outline-offset-8'],
    },
    {
      title: 'Ring Width',
      class: ['ring-0', 'ring-1', 'ring-2', 'ring', 'ring-4', 'ring-8', 'ring-inset'],
    },
    {
      title: 'Ring Color',
      class: ['ring-inherit', 'ring-current', 'ring-transparent', 'ring-black', 'ring-white', 'ring-slate-50', 'ring-slate-100', 'ring-slate-200'],
    },
    {
      title: 'Ring Offset Width',
      class: [
        'ring-offset-0',
        'ring-offset-1',
        'ring-offset-2',
        'ring-offset-4',
        'ring-offset-8',
      ],
    },
    {
      title: 'Ring Offset Color',
      class: [
        'ring-offset-inherit',
        'ring-offset-current',
        'ring-offset-transparent',
        'ring-offset-black',
        'ring-offset-white',
        'ring-offset-slate-50',
        'ring-offset-slate-100',
        'ring-offset-slate-200',
        'ring-offset-slate-300',
        'ring-offset-slate-400',
      ],
    },
  ]
  const effectsData=[
    {
      title: 'Box Shadow',
      class: [
        'shadow-sm',
        'shadow',
        'shadow-md',
        'shadow-lg',
        'shadow-xl',
        'shadow-2xl',
        'shadow-inner',
        'shadow-none',
      ],
    },
    {
      title: 'Box Shadow Color',
      class: [
        'shadow-inherit',
        'shadow-current',
        'shadow-transparent',
        'shadow-black',
        'shadow-white',
        'shadow-slate-50',
        'shadow-slate-100',
        'shadow-slate-200',
      ],
    },
    {
      title: 'Opacity',
      class: [
        'opacity-0',
        'opacity-5',
        'opacity-10',
        'opacity-20',
        'opacity-25',
        'opacity-30',
        'opacity-40',
        'opacity-50',
        'opacity-60',
        'opacity-70',
        'opacity-75',
        'opacity-80',
        'opacity-90',
        'opacity-95',
        'opacity-100',
      ],
    },
    {
      title: 'Mix Blend Mode',
      class: [
        'mix-blend-normal',
        'mix-blend-multiply',
        'mix-blend-screen',
        'mix-blend-overlay',
        'mix-blend-darken',
        'mix-blend-lighten',
        'mix-blend-color-dodge',
        'mix-blend-color-burn',
        'mix-blend-hard-light',
        'mix-blend-soft-light',
        'mix-blend-difference',
        'mix-blend-exclusion',
        'mix-blend-hue',
        'mix-blend-saturation',
        'mix-blend-color',
        'mix-blend-luminosity',
        'mix-blend-plus-lighter',
      ],
    },
    {
      title: 'Background Blend Mode',
      class: [
        'bg-blend-normal',
        'bg-blend-multiply',
        'bg-blend-screen',
        'bg-blend-overlay',
        'bg-blend-darken',
        'bg-blend-lighten',
        'bg-blend-color-dodge',
        'bg-blend-color-burn',
        'bg-blend-hard-light',
        'bg-blend-soft-light',
        'bg-blend-difference',
        'bg-blend-exclusion',
        'bg-blend-hue',
        'bg-blend-saturation',
        'bg-blend-color',
        'bg-blend-luminosity',
      ],
    },
  ]
  const filtersData=[
    {
      title: 'Blur',
      class: [
        'blur-none',
        'blur-sm',
        'blur',
        'blur-md',
        'blur-lg',
        'blur-xl',
        'blur-2xl',
        'blur-3xl',
      ],
    },
    {
      title: 'Brightness',
      class: [
        'brightness-0',
        'brightness-50',
        'brightness-75',
        'brightness-90',
        'brightness-95',
        'brightness-100',
        'brightness-105',
        'brightness-110',
        'brightness-125',
        'brightness-150',
        'brightness-200',
      ],
    },
    {
      title: 'Contrast',
      class: [
        'contrast-0',
        'contrast-50',
        'contrast-75',
        'contrast-100',
        'contrast-125',
        'contrast-150',
        'contrast-200',
      ],
    },
    {
      title: 'Drop Shadow',
      class: [
        'drop-shadow-sm',
        'drop-shadow',
        'drop-shadow-md',
        'drop-shadow-lg',
        'drop-shadow-xl',
        'drop-shadow-2xl',
        'drop-shadow-none',
      ],
    },
    {
      title: 'Grayscale',
      class: ['grayscale-0', 'grayscale'],
    },
    {
      title: 'Hue Rotate',
      class: [
        'hue-rotate-0',
        'hue-rotate-15',
        'hue-rotate-30',
        'hue-rotate-60',
        'hue-rotate-90',
        'hue-rotate-180',
      ],
    },
    {
      title: 'Invert',
      class: ['invert-0', 'invert'],
    },
    {
      title: 'Saturate',
      class: [
        'saturate-0',
        'saturate-50',
        'saturate-100',
        'saturate-150',
        'saturate-200',
      ],
    },
    {
      title: 'Sepia',
      class: ['sepia-0', 'sepia'],
    },
    {
      title: 'Backdrop Blur',
      class: [
        'backdrop-blur-none',
        'backdrop-blur-sm',
        'backdrop-blur',
        'backdrop-blur-md',
        'backdrop-blur-lg',
        'backdrop-blur-xl',
        'backdrop-blur-2xl',
        'backdrop-blur-3xl',
      ],
    },
    {
      title: 'Backdrop Brightness',
      class: [
        'backdrop-brightness-0',
        'backdrop-brightness-50',
        'backdrop-brightness-75',
        'backdrop-brightness-90',
        'backdrop-brightness-95',
        'backdrop-brightness-100',
        'backdrop-brightness-105',
        'backdrop-brightness-110',
        'backdrop-brightness-125',
        'backdrop-brightness-150',
        'backdrop-brightness-200',
      ],
    },
    {
      title: 'Backdrop Contrast',
      class: [
        'backdrop-contrast-0',
        'backdrop-contrast-50',
        'backdrop-contrast-75',
        'backdrop-contrast-100',
        'backdrop-contrast-125',
        'backdrop-contrast-150',
        'backdrop-contrast-200',
      ],
    },
    {
      title: 'Backdrop Grayscale',
      class: ['backdrop-grayscale-0', 'backdrop-grayscale'],
    },
    {
      title: 'Backdrop Hue Rotate',
      class: [
        'backdrop-hue-rotate-0',
        'backdrop-hue-rotate-15',
        'backdrop-hue-rotate-30',
        'backdrop-hue-rotate-60',
        'backdrop-hue-rotate-90',
        'backdrop-hue-rotate-180',
      ],
    },
    {
      title: 'Backdrop Invert',
      class: ['backdrop-invert-0', 'backdrop-invert'],
    },
    {
      title: 'Backdrop Opacity',
      class: [
        'backdrop-opacity-0',
        'backdrop-opacity-5',
        'backdrop-opacity-10',
        'backdrop-opacity-20',
        'backdrop-opacity-25',
        'backdrop-opacity-30',
        'backdrop-opacity-40',
        'backdrop-opacity-50',
        'backdrop-opacity-60',
        'backdrop-opacity-70',
        'backdrop-opacity-75',
        'backdrop-opacity-80',
        'backdrop-opacity-90',
        'backdrop-opacity-95',
        'backdrop-opacity-100',
      ],
    },
    {
      title: 'Backdrop Saturate',
      class: [
        'backdrop-saturate-0',
        'backdrop-saturate-50',
        'backdrop-saturate-100',
        'backdrop-saturate-150',
        'backdrop-saturate-200',
      ],
    },
    {
      title: 'Backdrop Sepia',
      class: ['backdrop-sepia-0', 'backdrop-sepia'],
    },
  ]
  return (
    <div >
      <h1 style={titleStyle}>Tailwind CSS</h1>
      <h1 style={titleStyle}>Layout</h1>
      <ResponsiveTable data={LayoutData} />
      <h1 style={titleStyle}>Flexbox & Grid</h1>
      <ResponsiveTable data={flexData} />
      <h1 style={titleStyle}>Spacing</h1>
      <ResponsiveTable data={spacingData} />
      <h1 style={titleStyle}>Sizing</h1>
      <ResponsiveTable data={sizingData} />
      <h1 style={titleStyle}>Typography</h1>
      <ResponsiveTable data={typographyData} />
      {/* <h1 style={titleStyle}>Backgrounds</h1>
      <ResponsiveTable data={backgroundsData} /> */}
      <h1 style={titleStyle}>Borders</h1>
      <ResponsiveTable data={bordersData} />
      {/* <h1 style={titleStyle}>Effects</h1>
      <ResponsiveTable data={effectsData} />
      <h1 style={titleStyle}>Filters</h1>
      <ResponsiveTable data={filtersData} /> */}
    </div>
  );
};

export default TailwindContent;


// only give me this details object of title and class not other anyone
// give data in this format 
// [    {
//       title: '',
//       class: ['',],
//     },..]

